name: PunchTree-Freebuild
main: net.punchtree.freebuild.PunchTreeFreebuildPlugin
version: 0.1.6
api-version: 1.19
depend: [WorldGuard, PunchTree-Util]
description: Custom functionality for the PunchTree freebuild server.
authors:
  - Cxom (Jeremy)
  - Sock (Mike)
commands:
  blocks:
    description: Access the remote block shop!
    aliases: [shop]
    usage: Invalid command! Please type /blocks or /shop to access the remote block shop.
    permission: ptfb.commands.blocks
  vskip:
    description: Vote to skip the current event. (Storms / Night-time)
    aliases: [voteskip,skipweather,skipnight]
    usage:  /vskip <weather / time>
    permission: ptfb.commands.ambientvoting.voteskip
  claimtest:
    description: A testing command to aid in development of the claim system
    usage: /claimtest <subcommand>
    permission: ptfb.in-progress-testing
  billiards:
    description: A catchall command for billiards stuff
    usage: /billiards <subcommand>
    permission: ptfb.in-progress-testing
  towerdefense:
    description: A catchall command for tower defense stuff
    usage: /towerdefense <subcommand>
    permission: ptfb.in-progress-testing
    aliases: [td]
  afk:
    description: Tell other player's you're going away from the keyboard.
    usage: /afk <optional user>
    permission: ptfb.commands.afk
