name: PunchTree-Freebuild
main: net.punchtree.freebuild.PunchTreeFreebuildPlugin
version: 0.1
api-version: 1.19
depend: [WorldGuard]
description: Custom functionality for the PunchTree freebuild server.
authors:
  - Cxom (Jeremy)
  - Sock (Mike)
commands:
  blocks:
    description: Access the remote block shop!
    aliases: [shop]
    usage: Invalid command! Please type /blocks or /shop to access the remote block shop.
    permission: ptfb.commands.blocks
  vskip:
    description: Vote to skip the current event. (Storms / Night-time)
    aliases: [voteskip,skipweather,skipnight]
    usage:  /vskip <weather / time>
    permission: ptfb.commands.ambientvoting.voteskip
  claimtest:
    description: A testing command to aid in development of the claim system
    usage: /claimtest <subcommand>
    permission: ptfb.in-progress-testing
  billiards:
    description: A catchall command for billiards stuff
    usage: /billiards <subcommand>
    permission: ptfb.in-progress-testing
